/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINPROCESSOR_H_526ED7A9__
#define __PLUGINPROCESSOR_H_526ED7A9__


#include "../JuceLibraryCode/JuceHeader.h"
#include "../JuceLibraryCode/JucePluginCharacteristics.h"
#include "Zynth.h"
#include "ChannelProcessor.h"
#include "AudioSample.h"

//==============================================================================
/**
*/
class mlrVSTAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    mlrVSTAudioProcessor();
    ~mlrVSTAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock);
    void releaseResources();
    void processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages);
    void reset();

    //==============================================================================
    bool hasEditor() const                  { return true; }
    AudioProcessorEditor* createEditor();

    //==============================================================================
    const String getName() const            { return JucePlugin_Name; }

    int getNumParameters();
    float getParameter (int index);
    void setParameter (int index, float newValue);
    const String getParameterName (int index);
    const String getParameterText (int index);

    const String getInputChannelName (int channelIndex) const;
    const String getOutputChannelName (int channelIndex) const;
    bool isInputChannelStereoPair (int index) const;
    bool isOutputChannelStereoPair (int index) const;

    bool acceptsMidi() const;
    bool producesMidi() const;

    //==============================================================================
    int getNumPrograms()                                                { return 0; }
    int getCurrentProgram()                                             { return 0; }
    void setCurrentProgram (int /*index*/)                              { }
    const String getProgramName (int /*index*/)                         { return String::empty; }
    void changeProgramName (int /*index*/, const String& /*newName*/)   { }
    ChannelProcessor* getChannelProcessor(const int &index) { return channelProcessorArray[index]; }

    //==============================================================================
    void getStateInformation (MemoryBlock& destData);
    void setStateInformation (const void* data, int sizeInBytes);

    //==============================================================================
    // These properties are public so that our editor component can access them
    // A bit of a hacky way to do it, but it's only a demo! Obviously in your own
    // code you'll do this much more neatly..

    // this is kept up to date with the midi messages that arrive, and the UI component
    // registers with it so it can represent the incoming messages
    MidiKeyboardState keyboardState;

    // this keeps a copy of the last set of time info that was acquired during an audio
    // callback - the UI component will read this and display it.
    AudioPlayHead::CurrentPositionInfo lastPosInfo;

    //==============================================================================
    // Note we may not need all these parameters, but if the host is to allow them,
    // to be automatable, we need to allow for the possibility.
    enum Parameters
    {
        masterGainParam = 0,
        delayParam,
        channel0GainParam,
        channel1GainParam,
        channel2GainParam,
        channel3GainParam,
        channel4GainParam,
        channel5GainParam,
        channel6GainParam,
        channel7GainParam,
        totalNumParams
    };

    float masterGain, delay;
    // individual channel volumes
    float channel0Gain, channel1Gain, channel2Gain, channel3Gain;
    float channel4Gain, channel5Gain, channel6Gain, channel7Gain;

    // add a sample to the sample pool
    void addNewSample();


    // set up the channels (can be used to change number of channels
    void buildChannelProcessorArray(const int &newNumChannels);

private:
    //==============================================================================

    // store array of samplePool objects
    OwnedArray<AudioSample> samplePool;

    AudioSampleBuffer delayBuffer;
    int delayPosition;

    // eventually this will be an array for all the channels
    int numChannels;
    // These are the seperate audio channels
    OwnedArray<ChannelProcessor> channelProcessorArray; 



    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (mlrVSTAudioProcessor);
};

#endif  // __PLUGINPROCESSOR_H_526ED7A9__
